swagger: "2.0"
info:
  description: "TCG server"
  version: "0.0.1"
  title: "TCG"
  termsOfService: "https://github.com/j4rio/tcg"
  contact:
    email: "jari.ojala@varjonvalo.fi"
  license:
    name: "MIT"
    url: "https://github.com/j4rio/tcg/blob/master/LICENSE"
host: "localhost:8080"
basePath: "/tcg/v1"
tags:
- name: "tcg"
  description: "Access point to TCG"
  externalDocs:
    description: "TCG in github.com"
    url: "https://github.com/j4rio/tcg"
schemes:
- "http"
paths:
  /{domain}/{state}:
    get:
      tags:
      - "tcg"
      summary: "Get an array of SEFs for a state in a domain"
      description: "Get an array of SEFs for a state in a domain"
      operationId: "getSEFArray"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "domain"
        in: "path"
        description: "context domain"
        required: true
        type: "string"
      - name: "state"
        in: "path"
        description: "state"
        required: true
        type: "string"
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/SEFArray"
        404:
          description: "unknown domain/state/sef"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "tcg"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Quaternion:
    description: "sef orientation matrix"
    type: "array"
    default: 
      [ 1, 0, 0, 0,
        0, 1, 0, 0,
        0, 0, 1, 0,
        0, 0, 0, 1
      ]
    items: 
      type: "number"
  SEF:
    type: "object"
    properties:
      initialState:
        type: "string"
        description: "initial state"
      triggers:
        type: array
        items: 
          type: "string"
      explain:
        type: "string"
        description: "explenation about the code fragment"
      fragment:
        type: "string"
        description: "code fragment"
      quaternion:
        $ref: "#/definitions/Quaternion"
      nextState:
        type: "string"
        description: "the next state"
  SEFArray:
    type: "array"
    items:
      $ref: "#/definitions/SEF"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
