swagger: "2.0"
info:
  description: "TCG server"
  version: "0.0.1"
  title: "TCG"
  termsOfService: "https://github.com/j4rio/tcg"
  contact:
    email: "jari.ojala@varjonvalo.fi"
  license:
    name: "MIT"
    url: "https://github.com/j4rio/tcg/blob/master/LICENSE"
host: "localhost:8080"
basePath: "/tcg/v1"
tags:
- name: "tcg"
  description: "Access point to TCG"
  externalDocs:
    description: "TCG in github.com"
    url: "https://github.com/j4rio/tcg"
schemes:
- "http"
paths:
  /:
    get:
      tags:
      - "tcg"
      summary: "Get an array of domains"
      description: "Get an array of domains"
      operationId: "getDomainArray"
      produces:
      - "application/json"
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/DomainArray"
        404:
          description: "no domains"
      x-swagger-router-controller: "tcg"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Domain:
    type: "object"
    properties:
      name:
        type: "string"
        description: "domain name"
      explain:
        type: "string"
        description: "explenation about the domain"
  DomainArray:
    type: "array"
    items:
      $ref: "#/definitions/Domain"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
